version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/CiCdLaravelProject
hooks:
  BeforeInstall:
    - location: devops/hooks/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: devops/hooks/AfterInstall.sh
      timeout: 300
      runas: root
