#!/bat/bash
version: 0.2
runtime-versions:
  php: 8.1
phases:
  install:
    commands:
      - apt-get update -y
      - echo Installing PHP 8.1...
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo Checking PHP version...
      - php -v
      - composer require phpunit/phpunit
  pre_build:
    commands:
      - composer install --no-interaction
      - cp .env.example .env
      - php artisan key:generate
  build:
    commands:
      - echo Build started on `date`
      - php artisan cache:clear
      - php artisan optimize
      - echo "Installing dependencies for frontend..."
      - npm install
  post_build:
    commands:
      - echo "Running tests..."
      - ./vendor/bin/phpunit
      - echo "Generating deployment artifact..."
artifacts:
  files:
    - "**/*"
  name: $(date +%Y-%m-%dT%H:%M:%S).zip

proxy:
  upload-artifacts: yes
  logs: yes
